from enum import Enum

class CMD(Enum):
    PING = 0
    SEND_TWO_INTS = 1
    SEND_THREE_FLOATS = 2
    ECHO = 3
    DANCE = 4
    SET_VEL = 5
    GET_TIME_MILLIS = 6
    GET_MANY_TIME_MILLIS = 7
    SEND_TIME_DATA = 8
    GET_TEMP_READINGS = 9
    GET_ROLL_PITCH = 10
    GET_GYRO_DATA = 11
    GET_ACC_GYRO_DATA = 12